### ISSUE TITLE
peer dependencies are old

### ISSUE THREAD

**Issue by martindemello** [phoenix-china/bucklescript-phx#11]
the peer dependencies currently list "bs-platform": "^1.8.0", "phoenix": "^1.2.1", which are quite out of date by now. from experimenting briefly it looks like things work against the latest bs-platform and phoenix, so it seems worth updating the dependencies.

**Comment by jackalcooper** [comment]
@martindemello Thanks for the tips. I will update it to the latest version and add support for phoenix live view as well.

**Comment by jackalcooper** [comment]
@martindemello I just found that this alternative [binding](https://github.com/yawaramin/bs-phoenix) which is better maintained and updated. The thing is that I don't have a real world use case to validate this project anymore. So probably it is a better idea to use the other implementation for now (if it serves what you need).

**Comment by jackalcooper** [comment]
fix in 0.1.4, published

**Comment by martindemello** [comment]
thanks, i'll check out the other bindings too!
