### ISSUE TITLE
Update to Reason 3 syntax

### ISSUE THREAD

**Issue by justgage** [phoenix-china/bucklescript-phx#3]
This isn't needed but it might confuse newcomers who are coming to reason. I think most of it can be done automatically as well: https://reasonml.github.io/blog/2017/10/27/reason3.html

**Comment by jackalcooper** [comment]
Sorry I don’t know what you want here. You want me to rewrite it or update
the example or what? 🤔

**Comment by justgage** [comment]
Mostly an example of how to use it in the newest syntax would be enough. I think when newcomers see that it's the old style they assume (wrongly in many cases) that it's not maintained.

Thanks, hopefully, my initial message came across kindly. 👐

**Comment by jackalcooper** [comment]
No worries. Nothing intensive here. 😸 I will do it later when I have more
time. Thanks for your advice!
