### ISSUE TITLE
Can't find `phoenix.js` during compilation

### ISSUE THREAD

**Issue by svoynow** [phoenix-china/bucklescript-phx#4]
```
ERROR in ./node_modules/bucklescript-phx/src/phx_socket.js
Module not found: Error: Can't resolve 'phoenix' in '/Users/foo/projects/phx_reason/assets/node_modules/bucklescript-phx/src'
 @ ./node_modules/bucklescript-phx/src/phx_socket.js 4:14-32
 @ ./node_modules/bucklescript-phx/src/phx.js
```

I'm trying to use this library in Reason code w/in a phoenix app (i.e. that lives in `/assets`. I've swapped in webpack for brunch, and I'm running `bsb` alongside `webpack` to compile my `.re` files. I'm using the new recommended "in source build" tactic so bsb compiles to .js which webpack then bundles.
Everything is working fine except for the above error. I have a feeling it might have something to do with the `in source build` thing, but I'm not sure. Any thoughts? Happy to provide `package.json` `bsconfig.json`, or even a whole repo if that would help.

**Comment by jackalcooper** [comment]
Hi @svoynow . If you look at the code of the binding, you would find that the it is a bs module syntax:
```
[@@bs.module "phoenix"]
```
So you must make sure this module is available when you are bundling the js. Anyway I will try to update the project with the latest bs release.
