### ISSUE TITLE
example doesnt work

### ISSUE THREAD

**Issue by mithereal** [phoenix-china/bucklescript-phx#5]
ive tried to make the example work but i keep getting syntax errors, im using the latest reason can you assist me on using i need to use phoenix for my client and i cant figure out how to fix. the in statements arent working as well im guessing theres an updated syntax

**Comment by jackalcooper** [comment]
I would like to assist you. The example is in ocaml, not reasonml. I might need to catch up with things because I was away from bucklescript for a while.

**Comment by mithereal** [comment]
Ok I'll try converting it to reason i just was unaware why it wasn't
working in New to reason and
Ocaml myself. Thx.

**Comment by mithereal** [comment]
i mostly have this working but i cant figure out where to call the handelevent fun, if i add it under the didmount or render funs it seemd to be out of scope, but if i add it above the component declaration and init the socket above the component , then join the channel apply the handelers i can see it in the js log but have no access to self because it hasnt been instantiated. example here https://gist.github.com/mithereal/7bdc25aa9b2667cf5704035ff8b064a8

**Comment by jackalcooper** [comment]
I don't understand why you put phoenix channel code in a separated file. I mean the lifetime of the socket should be related to your react component.
