### ISSUE TITLE
A question about licensing

### ISSUE THREAD

**Issue by pragdave** [phoenix-china/bucklescript-phx#9]
First, thank you for creating this binding.

I'm writing example code for what will either become an Elixir book or some online Elixir training. I'm thinking of using Reason for the client side.

This binding is licensed under LGPL 3. If I use it during the compilation of my sample code, will this result in my book or course content becoming part of a _combined work_? (because the binding is part of the build process)

If so, would you consider a dual license with something like the MIT license?

Thanks for reading this

Dave Thomas

**Comment by jackalcooper** [comment]
@pragdave Hi Dave. Very excited to hear from you! Long time big fan of your books!
As for the license, I will include MIT here but I am not sure if your concern would be addressed because ocaml and bucklescript are under LGPL.

**Comment by jackalcooper** [comment]
@pragdave If you decided to develop the content you just mentioned in ReasonML, please let me know. I will do some rewrite and update for the latest version of phoenix channel client.

**Comment by pragdave** [comment]
Ah, that's a good point. I'll ask over there, too.

Many thanks
